artifacts_config:
  artifacts_dir: artifacts

data_ingestion_config:
  dataset_download_url: https://raw.githubusercontent.com/entbappy/Branching-tutorial/master/books_data.zip
  dataset_dir: datasets
  ingested_dir: ingested
  raw_data_dir: raw_data

data_validation_config:
  clean_data_dir: clean_data
  books_csv_file: BX-Books.csv
  ratings_csv_file: BX-Book-Ratings.csv
  serialized_objects_dir: serialized_objects

data_transformation_config:
  transformed_data_dir: transformed_data

model_trainer_config:
  trained_model_dir: trained_model
  trained_model_name: model.pkl